from __future__ import annotations
import argparse, csv, hashlib, json
from pathlib import Path

def rows(p):
    with p.open(encoding="utf-8-sig", newline="") as f: return list(csv.DictReader(f))

def build(root: Path, output: Path):
    rules=rows(root/"rules/expert_rule_review_packet.csv")
    links=rows(root/"extraction/ai_draft_rule_evidence_links.csv")
    candidates={x["evidence_candidate_id"]:x for x in rows(root/"extraction/ai_full_text_evidence_candidates.csv")}
    packed=[]
    for r in rules:
        item={k:r[k] for k in ("review_item_id","rule_id","ingredient_id","population","threshold_value","threshold_unit","scope","locator","source_note","evidence_quote","message_ko","next_action_ko")}
        matched=sorted((x for x in links if x["rule_id"]==r["rule_id"]),key=lambda x:int(x["rank"]))
        item["evidence"]=[{k:candidates[x["evidence_candidate_id"]][k] for k in ("pmid","section_title","locator","source_sha256","evidence_text","signal_types","dose_mentions")} for x in matched]
        packed.append(item)
    data={"schema_version":"1.0.0","researcher":{"name":"권혁찬","student_id":"2021194024"},"rules":packed,"prefilled_decisions":0}
    output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text(HTML.replace("__DATA__",json.dumps(data,ensure_ascii=False).replace("</","<\\/")),encoding="utf-8")
    report={"output":str(output),"rules":len(packed),"evidence_candidates":sum(len(x["evidence"]) for x in packed),"prefilled_decisions":0,"bytes":output.stat().st_size,"sha256":hashlib.sha256(output.read_bytes()).hexdigest(),"external_dependencies":0}
    (output.parent/"expert_rule_review_html_manifest.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    return report

HTML=r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>권혁찬 안전 규칙 전문가 검토</title><style>
:root{font-family:Pretendard,-apple-system,BlinkMacSystemFont,"Noto Sans KR",sans-serif;color:#191f28;background:#f8fafc}*{box-sizing:border-box}body{margin:0}header,footer{position:fixed;left:0;right:0;background:#fffffff2;z-index:3;border:solid #e5e8eb;border-width:0 0 1px}footer{bottom:0;border-width:1px 0 0}.wrap,main{max-width:900px;margin:auto;padding:16px 24px}.head,.actions{display:flex;justify-content:space-between;gap:10px}.bar{height:4px;background:#edf0f3;margin-top:12px}.bar i{display:block;height:100%;background:#3182f6}main{padding-top:130px;padding-bottom:120px}h1{font-size:34px;line-height:1.35}.blue{color:#3182f6;font-weight:700}.muted{color:#6b7684;line-height:1.6}.card{background:white;border-radius:24px;padding:30px;box-shadow:0 8px 30px #001b370f}.meta,.choices{display:grid;grid-template-columns:1fr 1fr;gap:10px}.meta div{background:#f8fafc;border-radius:12px;padding:12px;color:#6b7684}.meta b{display:block;color:#333d4b}.message{background:#f2f6fa;border-radius:16px;padding:18px;margin:20px 0;line-height:1.6}details{border-top:1px solid #e5e8eb;padding:14px 2px}summary{cursor:pointer;font-weight:700}.small{font-size:13px;color:#6b7684;overflow-wrap:anywhere}.quote{line-height:1.65;margin:8px 0}.choices{grid-template-columns:repeat(3,1fr);margin-top:20px}button,input,textarea{font:inherit}button{border:0;border-radius:14px;padding:15px 20px;font-weight:700;cursor:pointer}.choice{border:1px solid #e5e8eb;background:white}.choice.sel{border-color:#3182f6;background:#edf6ff;color:#1b64da}.primary{background:#3182f6;color:white;flex:1}.primary:disabled{background:#b0c8e8}.secondary{background:#eef1f4}label{display:block;font-weight:700;margin:18px 0 8px}input,textarea{width:100%;border:1px solid #e5e8eb;border-radius:14px;padding:14px}textarea{min-height:90px}.hidden{display:none!important}.setup{max-width:640px;margin:auto}@media(max-width:600px){main{padding:110px 20px 120px}h1{font-size:28px}.card{padding:22px}.meta,.choices{grid-template-columns:1fr}}
</style></head><body><header><div class="wrap"><div class="head"><b>권혁찬 안전 규칙 전문가 검토</b><span id="count">시작 전</span></div><div class="bar"><i id="bar"></i></div></div></header><main><section id="setup" class="setup"><div class="blue">6개 규칙만 확인</div><h1>근거 후보를 읽고<br>규칙별로 한 번 판정하세요</h1><p class="muted">각 규칙의 원문 후보 10개를 펼쳐볼 수 있습니다. 자동 승인값은 없습니다.</p><div class="card"><label>검토자 이름</label><input id="reviewer"><label>자격·역할</label><input id="role" placeholder="예: 약사, 약학 교수"><p class="small">AI가 찾은 문단은 탐색 후보입니다. 기준값·인과성·임상 권고를 자동 확정하지 않습니다.</p><button id="start" class="primary">검토 시작</button></div></section><section id="review" class="hidden"><div id="eyebrow" class="blue"></div><h1 id="title"></h1><p class="muted">기준값, 범위, 문구, 공식 기준 위치, 전문 후보를 확인하세요.</p><div id="card" class="card"></div></section><section id="done" class="hidden"><div class="blue">검토 완료</div><h1>6개 규칙을 모두 확인했습니다</h1><div id="summary" class="card"></div><button id="download" class="primary">결과 JSON 저장</button></section></main><footer id="footer" class="hidden"><div class="wrap actions"><button id="prev" class="secondary">이전</button><button id="next" class="primary" disabled>판정 저장하고 다음</button></div></footer><script id="payload" type="application/json">__DATA__</script><script>
const D=JSON.parse(payload.textContent),K='kwon_expert_rule_review_v1';let S=JSON.parse(localStorage.getItem(K)||'{"cursor":0,"decisions":{}}');const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),save=()=>localStorage.setItem(K,JSON.stringify(S));
start.onclick=()=>{if(!reviewer.value.trim()||!role.value.trim())return alert('이름과 자격·역할을 입력하세요.');S.reviewer={name:reviewer.value.trim(),role:role.value.trim()};S.started_at=S.started_at||new Date().toISOString();save();setup.classList.add('hidden');review.classList.remove('hidden');footer.classList.remove('hidden');render()};
function render(){if(S.cursor>=D.rules.length)return finish();const r=D.rules[S.cursor],d=S.decisions[r.rule_id]||{};eyebrow.textContent=`안전 규칙 · ${S.cursor+1} / ${D.rules.length}`;title.textContent=`${r.ingredient_id} · ${r.threshold_value} ${r.threshold_unit}`;count.textContent=`${S.cursor+1} / ${D.rules.length}`;bar.style.width=`${S.cursor/D.rules.length*100}%`;card.innerHTML=`<div class="meta"><div>규칙 ID<b>${E(r.rule_id)}</b></div><div>대상<b>${E(r.population)}</b></div><div>적용 범위<b>${E(r.scope)}</b></div><div>공식 기준 위치<b>${E(r.locator)}</b></div></div><div class="message"><b>${E(r.message_ko)}</b><br>${E(r.next_action_ko)}</div><b>AI 전문 탐색 후보 ${r.evidence.length}건</b>${r.evidence.map((e,i)=>`<details ${i?'':'open'}><summary>${i+1}. PMID ${E(e.pmid)} · ${E(e.section_title)}</summary><div class="small">${E(e.locator)} · SHA-256 ${E(e.source_sha256)}</div><div class="quote">${E(e.evidence_text)}</div><div class="small">신호: ${E(e.signal_types)} / 용량: ${E(e.dose_mentions||'없음')} / 상태: AI 후보·사람 미검증</div></details>`).join('')}<div class="choices"><button class="choice ${d.decision==='approve'?'sel':''}" data-v="approve">승인</button><button class="choice ${d.decision==='revise'?'sel':''}" data-v="revise">수정 필요</button><button class="choice ${d.decision==='reject'?'sel':''}" data-v="reject">반려</button></div><label>확인 메모${d.decision==='approve'?' (선택)':' (수정·반려 시 필수)'}</label><textarea id="note">${E(d.note||'')}</textarea>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{d.decision=b.dataset.v;S.decisions[r.rule_id]=d;save();render()});note.oninput=e=>{d.note=e.target.value.trim();S.decisions[r.rule_id]=d;save();valid()};prev.disabled=!S.cursor;valid();scrollTo(0,0)}
const baseRender=render;render=function(){baseRender();if(S.cursor<D.rules.length){const r=D.rules[S.cursor],box=document.createElement('details');box.open=true;box.innerHTML=`<summary>공식 KDRI 표 전사 근거</summary><div class="quote">${E(r.evidence_quote)}</div><div class="small">${E(r.source_note)}</div>`;card.querySelector('.message').after(box)}};
function valid(){const r=D.rules[S.cursor],d=S.decisions[r.rule_id]||{};next.disabled=!d.decision||(d.decision!=='approve'&&!d.note)}next.onclick=()=>{const r=D.rules[S.cursor],d=S.decisions[r.rule_id];if(!d||!d.decision||(d.decision!=='approve'&&!d.note))return;const ok=d.decision==='approve';Object.assign(d,{review_item_id:r.review_item_id,reviewer_id:S.reviewer.name,reviewer_role:S.reviewer.role,reviewed_at:new Date().toISOString(),review_kind:'human_expert_rule_review',status:'completed',expert_approval_granted:ok,evidence_quote:r.evidence_quote,threshold_correct:ok,scope_correct:ok,conditions_correct:ok,exceptions_correct:ok,message_safe:ok,next_action_safe:ok,source_locator_verified:ok});S.cursor++;save();render()};prev.onclick=()=>{if(S.cursor){S.cursor--;save();render()}};
function finish(){review.classList.add('hidden');footer.classList.add('hidden');done.classList.remove('hidden');bar.style.width='100%';count.textContent='6 / 6';S.completed_at=new Date().toISOString();S.overall_status='completed';save();const v=Object.values(S.decisions);summary.innerHTML=`승인 ${v.filter(x=>x.decision==='approve').length}건 · 수정 필요 ${v.filter(x=>x.decision==='revise').length}건 · 반려 ${v.filter(x=>x.decision==='reject').length}건<br><span class="small">결과는 importer 검증 후에만 규칙 상태에 반영됩니다.</span>`}download.onclick=()=>{const b=new Blob([JSON.stringify({schema_version:'1.0.0',review_type:'expert_rule_review',researcher:D.researcher,...S,exported_at:new Date().toISOString(),required_rule_count:D.rules.length},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='권혁찬_전문가_규칙검토결과.json';a.click()};
</script></body></html>'''

def main():
    p=argparse.ArgumentParser();p.add_argument("--root",type=Path,default=Path("research_v3"));p.add_argument("--output",type=Path);a=p.parse_args();root=a.root.resolve();out=a.output.resolve() if a.output else root/"human_review_minimal/전문가_규칙검토.html";print(json.dumps(build(root,out),ensure_ascii=False,indent=2));return 0
if __name__=="__main__": raise SystemExit(main())
