from __future__ import annotations
import argparse,csv,hashlib,json
from pathlib import Path

def build(source:Path,output:Path):
    with source.open(encoding="utf-8-sig",newline="") as f:rows=list(csv.DictReader(f))
    items=[]
    for r in rows:
        payload=json.loads(r["input_json"])
        items.append({"scenario_id":r["scenario_id"],"scenario_type":r["scenario_type"],"input":payload})
    data={"schema_version":"1.0.0","items":items,"prefilled_gold_labels":0,"predictions_exposed":0}
    output.parent.mkdir(parents=True,exist_ok=True);output.write_text(HTML.replace("__DATA__",json.dumps(data,ensure_ascii=False).replace("</","<\\/")),encoding="utf-8")
    report={"output":str(output),"scenarios":len(items),"prefilled_gold_labels":0,"predictions_exposed":0,"sha256":hashlib.sha256(output.read_bytes()).hexdigest()}
    (output.parent/"independent_scenario_review_html_manifest.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");return report

HTML=r'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>권혁찬 독립 시나리오 확정</title><style>
:root{font-family:Pretendard,-apple-system,BlinkMacSystemFont,"Noto Sans KR",sans-serif;color:#191f28;background:#f8fafc}*{box-sizing:border-box}body{margin:0}header,footer{position:fixed;left:0;right:0;background:#fffffff2;z-index:3;border-bottom:1px solid #e5e8eb}footer{bottom:0;border-top:1px solid #e5e8eb;border-bottom:0}.wrap,main{max-width:820px;margin:auto;padding:16px 24px}.head,.actions{display:flex;justify-content:space-between;gap:10px}.bar{height:4px;background:#edf0f3;margin-top:12px}.bar i{display:block;height:100%;background:#3182f6}main{padding-top:125px;padding-bottom:120px}h1{font-size:34px}.blue{color:#3182f6;font-weight:700}.muted,.small{color:#6b7684;line-height:1.6}.small{font-size:13px}.card{background:white;border-radius:24px;padding:30px;box-shadow:0 8px 30px #001b370f}.input{background:#f2f6fa;border-radius:16px;padding:18px;line-height:1.7;overflow-wrap:anywhere}.choices{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:22px}button,input,textarea{font:inherit}button{border:0;border-radius:14px;padding:15px 20px;font-weight:700;cursor:pointer}.choice{background:white;border:1px solid #e5e8eb}.choice.sel{border-color:#3182f6;background:#edf6ff;color:#1b64da}.primary{background:#3182f6;color:white;flex:1}.primary:disabled{background:#b0c8e8}.secondary{background:#eef1f4}label{display:block;font-weight:700;margin:18px 0 8px}input,textarea{width:100%;border:1px solid #e5e8eb;border-radius:14px;padding:14px}textarea{min-height:80px}.hidden{display:none!important}.setup{max-width:620px;margin:auto}@media(max-width:600px){main{padding:105px 20px 115px}h1{font-size:28px}.card{padding:22px}.choices{grid-template-columns:1fr}}
</style></head><body><header><div class="wrap"><div class="head"><b>권혁찬 독립 시나리오 확정</b><span id="count">시작 전</span></div><div class="bar"><i id="bar"></i></div></div></header><main><section id="setup" class="setup"><div class="blue">12개 사례 · 블라인드 판정</div><h1>입력만 보고<br>경고 필요 여부를 정하세요</h1><p class="muted">엔진 예측과 개발 정답은 표시하지 않습니다. 각 사례를 먼저 잠근 뒤 별도 평가합니다.</p><div class="card"><label>독립 판정자 이름</label><input id="reviewer"><label>자격·역할</label><input id="role" placeholder="예: 약사, 약학 교수"><button id="start" class="primary">판정 시작</button></div></section><section id="review" class="hidden"><div id="eyebrow" class="blue"></div><h1 id="title"></h1><p class="muted">이 입력에서 안전성 경고가 필요한지만 판단하세요.</p><div id="card" class="card"></div></section><section id="done" class="hidden"><div class="blue">잠금 완료</div><h1>12개 독립 정답을 확정했습니다</h1><div id="summary" class="card"></div><button id="download" class="primary">잠금 결과 JSON 저장</button></section></main><footer id="footer" class="hidden"><div class="wrap actions"><button id="prev" class="secondary">이전</button><button id="next" class="primary" disabled>판정 잠그고 다음</button></div></footer><script id="payload" type="application/json">__DATA__</script><script>
const D=JSON.parse(payload.textContent),K='kwon_independent_scenario_review_v1';let S=JSON.parse(localStorage.getItem(K)||'{"cursor":0,"decisions":{}}');const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),save=()=>localStorage.setItem(K,JSON.stringify(S));start.onclick=()=>{if(!reviewer.value.trim()||!role.value.trim())return alert('이름과 자격·역할을 입력하세요.');S.reviewer={name:reviewer.value.trim(),role:role.value.trim()};S.started_at=S.started_at||new Date().toISOString();save();setup.classList.add('hidden');review.classList.remove('hidden');footer.classList.remove('hidden');render()};
function render(){if(S.cursor>=D.items.length)return finish();const r=D.items[S.cursor],d=S.decisions[r.scenario_id]||{};eyebrow.textContent=`독립 사례 · ${S.cursor+1} / ${D.items.length}`;title.textContent=r.scenario_id;count.textContent=`${S.cursor+1} / ${D.items.length}`;bar.style.width=`${S.cursor/D.items.length*100}%`;card.innerHTML=`<div class="input"><b>입력</b><br>${Object.entries(r.input).map(([k,v])=>`${E(k)}: ${E(v)}`).join('<br>')}</div><div class="choices"><button class="choice ${d.label==='warning'?'sel':''}" data-v="warning">경고 필요</button><button class="choice ${d.label==='no_warning'?'sel':''}" data-v="no_warning">경고 불필요</button></div><label>판정 메모 (선택)</label><textarea id="note">${E(d.note||'')}</textarea><p class="small">엔진 예측·개발 정답·critical 분류 비공개</p>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{d.label=b.dataset.v;S.decisions[r.scenario_id]=d;save();render()});note.oninput=e=>{d.note=e.target.value.trim();S.decisions[r.scenario_id]=d;save()};next.disabled=!d.label;prev.disabled=!S.cursor;scrollTo(0,0)}
next.onclick=()=>{const r=D.items[S.cursor],d=S.decisions[r.scenario_id];if(!d?.label)return;Object.assign(d,{adjudicator_id:S.reviewer.name,adjudicator_role:S.reviewer.role,adjudicated_at:new Date().toISOString(),review_kind:'independent_human_scenario_adjudication',locked_before_test:true,status:'completed'});S.cursor++;save();render()};prev.onclick=()=>{if(S.cursor){S.cursor--;save();render()}};function finish(){review.classList.add('hidden');footer.classList.add('hidden');done.classList.remove('hidden');bar.style.width='100%';count.textContent='12 / 12';S.completed_at=new Date().toISOString();S.overall_status='completed';save();summary.textContent='잠금 정답 12건 · 엔진 예측 노출 0건'}download.onclick=()=>{const b=new Blob([JSON.stringify({schema_version:'1.0.0',review_type:'independent_scenario_adjudication',...S,exported_at:new Date().toISOString(),required_scenario_count:D.items.length},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='권혁찬_독립시나리오_잠금결과.json';a.click()};
</script></body></html>'''
def main():
    p=argparse.ArgumentParser();p.add_argument("--source",type=Path,default=Path("research_v3/human_review_minimal/05_독립시나리오_12건_확정.csv"));p.add_argument("--output",type=Path,default=Path("research_v3/human_review_minimal/독립시나리오_확정.html"));a=p.parse_args();print(json.dumps(build(a.source,a.output),ensure_ascii=False,indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
